version: '2.1'

networks:
  default-network:
    driver: bridge

services:
  mysql:
    image: mysql:8
    ports:
      - "${DOCKER_MYSQL_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=sites_stat
    volumes:
      - ./persistent_data/mysql:/var/lib/mysql
    networks:
      - default-network